# use the fast container-based test runner instead of the slow VM runner
sudo: false

language: go

go:
  - 1.x

# only clone the most recent commit
git:
  depth: 1

# skip the install step. don't `go get` deps. only build with code in vendor/
install: true

notifications:
  email: false

# like before_script, but with set +e
script:
  - golangci-lint run
  - go test -v -race ./...