# use the fast container-based test runner instead of the slow VM runner
sudo: false

language: go

go:
  - 1.x

# only clone the most recent commit
git:
  depth: 1


notifications:
  email: false

# like script, but with set -e
before_script:
  - go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint

# like before_script, but with set +e
script:
  - golangci-lint run
  - go test -v -race ./...